# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

EVENT_TYPES = ["Workshop", "Party", "Competition", "Festival", "Social Dance", "Concert", "Class"]
DANCE_CATEGORIES = ["Salsa", "Bachata", "Kizomba", "Ballet", "Contemporary", "Hip Hop", "Tango", "Swing"]
CURRENCIES = ["USD", "EUR", "GBP"]

events_data = [
  {
    event_name: "Miami Salsa Congress",
    description: "Join us for the biggest salsa event in Miami! Three days of workshops, social dancing, and performances from world-renowned dancers. Perfect for all levels, from beginners to advanced dancers.",
    location: "Miami Beach Convention Center",
    address: "1901 Convention Center Drive",
    city: "Miami Beach",
    state: "Florida",
    country: "USA",
    ticket_price: 199.99,
    currency: "USD",
    event_type: "Festival",
    event_category: "Salsa",
    image_url: "https://example.com/images/miami-salsa-congress.jpg",
    video_url: "https://example.com/videos/msc-promo.mp4",
    social_media: "https://instagram.com/miamisalsacongress",
    website: "https://miamisalsacongress.com",
    booking_url: "https://miamisalsacongress.com/tickets",
    notes: "Early bird tickets available until March 1st. Includes access to all workshops and parties."
  },
  {
    event_name: "Paris Tango Night",
    description: "Experience the magic of Argentine Tango in the heart of Paris. Live music, professional performances, and open dancing all night long.",
    location: "Le Petit Palais",
    address: "15 Rue de la Danse",
    city: "Paris",
    state: "Île-de-France",
    country: "France",
    ticket_price: 45.00,
    currency: "EUR",
    event_type: "Party",
    event_category: "Tango",
    image_url: "https://example.com/images/paris-tango.jpg",
    video_url: "https://example.com/videos/paris-tango.mp4",
    social_media: "https://instagram.com/paristangonight",
    website: "https://paristangonight.fr",
    booking_url: "https://paristangonight.fr/tickets",
    notes: "Dress code: Elegant. Basic tango knowledge required."
  },
  {
    event_name: "London Street Dance Championship",
    description: "The UK's premier street dance competition featuring the best crews from around the world. Categories include breaking, popping, hip hop, and all-styles battles.",
    location: "O2 Arena",
    address: "Peninsula Square",
    city: "London",
    state: "Greater London",
    country: "UK",
    ticket_price: 75.00,
    currency: "GBP",
    event_type: "Competition",
    event_category: "Hip Hop",
    image_url: "https://example.com/images/london-street-dance.jpg",
    video_url: "https://example.com/videos/lsdc-promo.mp4",
    social_media: "https://instagram.com/ldnstreetdance",
    website: "https://londonstreetdance.co.uk",
    booking_url: "https://londonstreetdance.co.uk/tickets",
    notes: "Competitor registration closes one month before the event."
  },
  {
    event_name: "Bachata Sensual Workshop",
    description: "Learn the art of Bachata Sensual from world champions. This intensive workshop covers musicality, body movement, and partner work.",
    location: "Dance Studio 23",
    address: "123 Dance Avenue",
    city: "Barcelona",
    state: "Catalonia",
    country: "Spain",
    ticket_price: 80.00,
    currency: "EUR",
    event_type: "Workshop",
    event_category: "Bachata",
    image_url: "https://example.com/images/bachata-workshop.jpg",
    video_url: "https://example.com/videos/bachata-promo.mp4",
    social_media: "https://instagram.com/bachatasensual",
    website: "https://bachataworkshop.es",
    booking_url: "https://bachataworkshop.es/register",
    notes: "Intermediate level required. Partners not necessary."
  },
  {
    event_name: "Swan Lake Ballet",
    description: "The Royal Ballet presents Tchaikovsky's masterpiece Swan Lake. Experience this timeless story of love, betrayal, and transformation.",
    location: "Royal Opera House",
    address: "Bow Street",
    city: "London",
    state: "Greater London",
    country: "UK",
    ticket_price: 150.00,
    currency: "GBP",
    event_type: "Concert",
    event_category: "Ballet",
    image_url: "https://example.com/images/swan-lake.jpg",
    video_url: "https://example.com/videos/swan-lake-promo.mp4",
    social_media: "https://instagram.com/royalballet",
    website: "https://roh.org.uk",
    booking_url: "https://roh.org.uk/tickets/swan-lake",
    notes: "Running time: 3 hours including two intervals."
  },
  {
    event_name: "Tokyo Dance Fusion Festival",
    description: "Experience the unique blend of traditional Japanese dance and modern street styles. This three-day festival features workshops in hip hop, breakdancing, and traditional Japanese dance forms, culminating in a spectacular showcase performance.",
    location: "Tokyo Metropolitan Gymnasium",
    address: "2-1-1 Jinnan",
    city: "Shibuya",
    state: "Tokyo",
    country: "Japan",
    ticket_price: 15000.00,
    currency: "JPY",
    event_type: "Festival",
    event_category: "Contemporary",
    image_url: "https://example.com/images/tokyo-fusion.jpg",
    video_url: "https://example.com/videos/tokyo-fusion.mp4",
    social_media: "https://instagram.com/tokyodancefusion",
    website: "https://tokyodancefusion.jp",
    booking_url: "https://tokyodancefusion.jp/tickets",
    notes: "Translation services available. All skill levels welcome."
  },
  {
    event_name: "Brazilian Zouk Intensive",
    description: "Join world champions Ricardo and Karen for an intensive weekend of Brazilian Zouk. Master the flowing movements and deep connection that make this dance so captivating. Special focus on musicality and advanced movement techniques.",
    location: "Copacabana Dance Studio",
    address: "Avenida Atlântica 1702",
    city: "Rio de Janeiro",
    state: "Rio de Janeiro",
    country: "Brazil",
    ticket_price: 450.00,
    currency: "BRL",
    event_type: "Workshop",
    event_category: "Zouk",
    image_url: "https://example.com/images/zouk-intensive.jpg",
    video_url: "https://example.com/videos/zouk-promo.mp4",
    social_media: "https://instagram.com/brazilianzouk",
    website: "https://brazilianzoukrij.com",
    booking_url: "https://brazilianzoukrij.com/intensive",
    notes: "Intermediate to advanced level. Partner required. Limited to 30 couples."
  },
  {
    event_name: "Urban Dance Camp Berlin",
    description: "Europe's biggest urban dance summer camp returns! Two weeks of intensive training in breaking, popping, locking, and house dance. Learn from pioneering dancers and connect with the global street dance community.",
    location: "Berlin Dance Academy",
    address: "Frankfurter Allee 91",
    city: "Berlin",
    state: "Berlin",
    country: "Germany",
    ticket_price: 599.00,
    currency: "EUR",
    event_type: "Workshop",
    event_category: "Hip Hop",
    image_url: "https://example.com/images/berlin-camp.jpg",
    video_url: "https://example.com/videos/berlin-camp.mp4",
    social_media: "https://instagram.com/urbandancecamp",
    website: "https://urbandancecamp.de",
    booking_url: "https://urbandancecamp.de/register",
    notes: "Accommodation packages available. All classes taught in English. Ages 16+"
  },
  {
    event_name: "Vienna Waltz Ball",
    description: "Step into the glamorous world of Viennese ballroom dance at this annual gala event. Live orchestra, professional demonstrations, and open dancing in the stunning Schönbrunn Palace. Traditional opening ceremony with debutantes.",
    location: "Schönbrunn Palace",
    address: "Schönbrunner Schlossstraße 47",
    city: "Vienna",
    state: "Vienna",
    country: "Austria",
    ticket_price: 280.00,
    currency: "EUR",
    event_type: "Party",
    event_category: "Ballroom",
    image_url: "https://example.com/images/vienna-ball.jpg",
    video_url: "https://example.com/videos/vienna-ball.mp4",
    social_media: "https://instagram.com/viennawaltzball",
    website: "https://viennaball.com",
    booking_url: "https://viennaball.com/tickets",
    notes: "Formal attire required. Includes champagne reception and midnight buffet."
  },
  {
    event_name: "Flamenco Masters Series",
    description: "An intimate workshop series with Spain's leading flamenco artists. Learn the passionate art of flamenco dance, focusing on technique, expression, and rhythmic patterns. Special sessions on castanets and fan work.",
    location: "Teatro Flamenco",
    address: "Calle del Amor 23",
    city: "Seville",
    state: "Andalusia",
    country: "Spain",
    ticket_price: 350.00,
    currency: "EUR",
    event_type: "Workshop",
    event_category: "Flamenco",
    image_url: "https://example.com/images/flamenco-masters.jpg",
    video_url: "https://example.com/videos/flamenco-promo.mp4",
    social_media: "https://instagram.com/flamencomatters",
    website: "https://flamencomasters.es",
    booking_url: "https://flamencomasters.es/workshops",
    notes: "Live guitar accompaniment. Shoes and practice skirts available for rent."
  }
]

events_data.each do |event_data|
  Event.create!(event_data)
end
