# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

EVENT_TYPES = ["Workshop", "Party", "Competition", "Festival", "Social Dance", "Concert", "Class"]
DANCE_CATEGORIES = ["Salsa", "Bachata", "Kizomba", "Ballet", "Contemporary", "Hip Hop", "Tango", "Swing"]
CURRENCIES = ["USD", "EUR", "GBP"]

events_data = [
  {
    event_name: "Miami Salsa Congress",
    description: "Join us for the biggest salsa event in Miami! Three days of workshops, social dancing, and performances from world-renowned dancers. Perfect for all levels, from beginners to advanced dancers.",
    location: "Miami Beach Convention Center",
    address: "1901 Convention Center Drive",
    city: "Miami Beach",
    state: "Florida",
    country: "USA",
    ticket_price: 199.99,
    currency: "USD",
    event_type: "Festival",
    event_category: "Salsa",
    image_url: "https://example.com/images/miami-salsa-congress.jpg",
    video_url: "https://example.com/videos/msc-promo.mp4",
    social_media: "https://instagram.com/miamisalsacongress",
    website: "https://miamisalsacongress.com",
    booking_url: "https://miamisalsacongress.com/tickets",
    notes: "Early bird tickets available until March 1st. Includes access to all workshops and parties."
  },
  {
    event_name: "Paris Tango Night",
    description: "Experience the magic of Argentine Tango in the heart of Paris. Live music, professional performances, and open dancing all night long.",
    location: "Le Petit Palais",
    address: "15 Rue de la Danse",
    city: "Paris",
    state: "Île-de-France",
    country: "France",
    ticket_price: 45.00,
    currency: "EUR",
    event_type: "Party",
    event_category: "Tango",
    image_url: "https://example.com/images/paris-tango.jpg",
    video_url: "https://example.com/videos/paris-tango.mp4",
    social_media: "https://instagram.com/paristangonight",
    website: "https://paristangonight.fr",
    booking_url: "https://paristangonight.fr/tickets",
    notes: "Dress code: Elegant. Basic tango knowledge required."
  },
  {
    event_name: "London Street Dance Championship",
    description: "The UK's premier street dance competition featuring the best crews from around the world. Categories include breaking, popping, hip hop, and all-styles battles.",
    location: "O2 Arena",
    address: "Peninsula Square",
    city: "London",
    state: "Greater London",
    country: "UK",
    ticket_price: 75.00,
    currency: "GBP",
    event_type: "Competition",
    event_category: "Hip Hop",
    image_url: "https://example.com/images/london-street-dance.jpg",
    video_url: "https://example.com/videos/lsdc-promo.mp4",
    social_media: "https://instagram.com/ldnstreetdance",
    website: "https://londonstreetdance.co.uk",
    booking_url: "https://londonstreetdance.co.uk/tickets",
    notes: "Competitor registration closes one month before the event."
  },
  {
    event_name: "Bachata Sensual Workshop",
    description: "Learn the art of Bachata Sensual from world champions. This intensive workshop covers musicality, body movement, and partner work.",
    location: "Dance Studio 23",
    address: "123 Dance Avenue",
    city: "Barcelona",
    state: "Catalonia",
    country: "Spain",
    ticket_price: 80.00,
    currency: "EUR",
    event_type: "Workshop",
    event_category: "Bachata",
    image_url: "https://example.com/images/bachata-workshop.jpg",
    video_url: "https://example.com/videos/bachata-promo.mp4",
    social_media: "https://instagram.com/bachatasensual",
    website: "https://bachataworkshop.es",
    booking_url: "https://bachataworkshop.es/register",
    notes: "Intermediate level required. Partners not necessary."
  },
  {
    event_name: "Swan Lake Ballet",
    description: "The Royal Ballet presents Tchaikovsky's masterpiece Swan Lake. Experience this timeless story of love, betrayal, and transformation.",
    location: "Royal Opera House",
    address: "Bow Street",
    city: "London",
    state: "Greater London",
    country: "UK",
    ticket_price: 150.00,
    currency: "GBP",
    event_type: "Concert",
    event_category: "Ballet",
    image_url: "https://example.com/images/swan-lake.jpg",
    video_url: "https://example.com/videos/swan-lake-promo.mp4",
    social_media: "https://instagram.com/royalballet",
    website: "https://roh.org.uk",
    booking_url: "https://roh.org.uk/tickets/swan-lake",
    notes: "Running time: 3 hours including two intervals."
  },
  {
    event_name: "Tokyo Dance Fusion Festival",
    description: "Experience the unique blend of traditional Japanese dance and modern street styles. This three-day festival features workshops in hip hop, breakdancing, and traditional Japanese dance forms, culminating in a spectacular showcase performance.",
    location: "Tokyo Metropolitan Gymnasium",
    address: "2-1-1 Jinnan",
    city: "Shibuya",
    state: "Tokyo",
    country: "Japan",
    ticket_price: 15000.00,
    currency: "JPY",
    event_type: "Festival",
    event_category: "Contemporary",
    image_url: "https://example.com/images/tokyo-fusion.jpg",
    video_url: "https://example.com/videos/tokyo-fusion.mp4",
    social_media: "https://instagram.com/tokyodancefusion",
    website: "https://tokyodancefusion.jp",
    booking_url: "https://tokyodancefusion.jp/tickets",
    notes: "Translation services available. All skill levels welcome."
  },
  {
    event_name: "Brazilian Zouk Intensive",
    description: "Join world champions Ricardo and Karen for an intensive weekend of Brazilian Zouk. Master the flowing movements and deep connection that make this dance so captivating. Special focus on musicality and advanced movement techniques.",
    location: "Copacabana Dance Studio",
    address: "Avenida Atlântica 1702",
    city: "Rio de Janeiro",
    state: "Rio de Janeiro",
    country: "Brazil",
    ticket_price: 450.00,
    currency: "BRL",
    event_type: "Workshop",
    event_category: "Zouk",
    image_url: "https://example.com/images/zouk-intensive.jpg",
    video_url: "https://example.com/videos/zouk-promo.mp4",
    social_media: "https://instagram.com/brazilianzouk",
    website: "https://brazilianzoukrij.com",
    booking_url: "https://brazilianzoukrij.com/intensive",
    notes: "Intermediate to advanced level. Partner required. Limited to 30 couples."
  },
  {
    event_name: "Urban Dance Camp Berlin",
    description: "Europe's biggest urban dance summer camp returns! Two weeks of intensive training in breaking, popping, locking, and house dance. Learn from pioneering dancers and connect with the global street dance community.",
    location: "Berlin Dance Academy",
    address: "Frankfurter Allee 91",
    city: "Berlin",
    state: "Berlin",
    country: "Germany",
    ticket_price: 599.00,
    currency: "EUR",
    event_type: "Workshop",
    event_category: "Hip Hop",
    image_url: "https://example.com/images/berlin-camp.jpg",
    video_url: "https://example.com/videos/berlin-camp.mp4",
    social_media: "https://instagram.com/urbandancecamp",
    website: "https://urbandancecamp.de",
    booking_url: "https://urbandancecamp.de/register",
    notes: "Accommodation packages available. All classes taught in English. Ages 16+"
  },
  {
    event_name: "Vienna Waltz Ball",
    description: "Step into the glamorous world of Viennese ballroom dance at this annual gala event. Live orchestra, professional demonstrations, and open dancing in the stunning Schönbrunn Palace. Traditional opening ceremony with debutantes.",
    location: "Schönbrunn Palace",
    address: "Schönbrunner Schlossstraße 47",
    city: "Vienna",
    state: "Vienna",
    country: "Austria",
    ticket_price: 280.00,
    currency: "EUR",
    event_type: "Party",
    event_category: "Ballroom",
    image_url: "https://example.com/images/vienna-ball.jpg",
    video_url: "https://example.com/videos/vienna-ball.mp4",
    social_media: "https://instagram.com/viennawaltzball",
    website: "https://viennaball.com",
    booking_url: "https://viennaball.com/tickets",
    notes: "Formal attire required. Includes champagne reception and midnight buffet."
  },
  {
    event_name: "Flamenco Masters Series",
    description: "An intimate workshop series with Spain's leading flamenco artists. Learn the passionate art of flamenco dance, focusing on technique, expression, and rhythmic patterns. Special sessions on castanets and fan work.",
    location: "Teatro Flamenco",
    address: "Calle del Amor 23",
    city: "Seville",
    state: "Andalusia",
    country: "Spain",
    ticket_price: 350.00,
    currency: "EUR",
    event_type: "Workshop",
    event_category: "Flamenco",
    image_url: "https://example.com/images/flamenco-masters.jpg",
    video_url: "https://example.com/videos/flamenco-promo.mp4",
    social_media: "https://instagram.com/flamencomatters",
    website: "https://flamencomasters.es",
    booking_url: "https://flamencomasters.es/workshops",
    notes: "Live guitar accompaniment. Shoes and practice skirts available for rent."
  },

  {
    event_name: "New York Salsa Festival",
    description: "An electrifying night of salsa music and dance featuring live performances from top salsa bands and world-class dancers.",
    location: "Madison Square Garden",
    address: "4 Pennsylvania Plaza",
    city: "New York",
    state: "New York",
    country: "USA",
    ticket_price: 120.00,
    currency: "USD",
    event_type: "Festival",
    event_category: "Salsa",
    image_url: "https://example.com/images/ny-salsa-festival.jpg",
    video_url: "https://example.com/videos/ny-salsa-festival.mp4",
    social_media: "https://instagram.com/nysalsafestival",
    website: "https://nysalsafestival.com",
    booking_url: "https://nysalsafestival.com/tickets",
    notes: "VIP tickets include meet & greet with artists."
  },
  {
    event_name: "Buenos Aires Tango Marathon",
    description: "A 4-day tango marathon with non-stop dancing, top DJs, and international tango lovers gathering in the heart of Argentina.",
    location: "La Viruta Tango Club",
    address: "Armenia 1366",
    city: "Buenos Aires",
    state: "Buenos Aires",
    country: "Argentina",
    ticket_price: 90.00,
    currency: "ARS",
    event_type: "Marathon",
    event_category: "Tango",
    image_url: "https://example.com/images/ba-tango-marathon.jpg",
    video_url: "https://example.com/videos/ba-tango-marathon.mp4",
    social_media: "https://instagram.com/batango",
    website: "https://batangomarathon.com",
    booking_url: "https://batangomarathon.com/register",
    notes: "Marathon pass includes snacks and drinks."
  },
  {
    event_name: "Los Angeles Kizomba Festival",
    description: "An immersive experience into the world of Kizomba, featuring dance workshops, parties, and international instructors.",
    location: "Hilton Hotel Downtown",
    address: "777 Figueroa Street",
    city: "Los Angeles",
    state: "California",
    country: "USA",
    ticket_price: 180.00,
    currency: "USD",
    event_type: "Festival",
    event_category: "Kizomba",
    image_url: "https://example.com/images/la-kizomba.jpg",
    video_url: "https://example.com/videos/la-kizomba.mp4",
    social_media: "https://instagram.com/lakizombafestival",
    website: "https://lakizombafestival.com",
    booking_url: "https://lakizombafestival.com/tickets",
    notes: "Full pass includes access to all workshops and parties."
  },
  {
    event_name: "Seoul Hip Hop Jam",
    description: "A high-energy gathering of the best hip hop dancers, featuring battles, showcases, and workshops in the vibrant city of Seoul.",
    location: "COEX Convention Center",
    address: "513 Yeongdong-daero",
    city: "Seoul",
    state: "Seoul",
    country: "South Korea",
    ticket_price: 65.00,
    currency: "KRW",
    event_type: "Battle",
    event_category: "Hip Hop",
    image_url: "https://example.com/images/seoul-hip-hop.jpg",
    video_url: "https://example.com/videos/seoul-hip-hop.mp4",
    social_media: "https://instagram.com/seoulhiphopjam",
    website: "https://seoulhiphopjam.com",
    booking_url: "https://seoulhiphopjam.com/tickets",
    notes: "Cash prizes for battle winners."
  },
  {
    event_name: "Dubai Latin Dance Congress",
    description: "A luxurious dance experience in Dubai featuring Salsa, Bachata, and Kizomba workshops, pool parties, and gala nights.",
    location: "Atlantis The Palm",
    address: "Crescent Road",
    city: "Dubai",
    state: "Dubai",
    country: "UAE",
    ticket_price: 350.00,
    currency: "AED",
    event_type: "Congress",
    event_category: "Latin Dance",
    image_url: "https://example.com/images/dubai-latin.jpg",
    video_url: "https://example.com/videos/dubai-latin.mp4",
    social_media: "https://instagram.com/dubailatincongress",
    website: "https://dubailatincongress.com",
    booking_url: "https://dubailatincongress.com/tickets",
    notes: "Luxury hotel stay packages available."
  },
  {
    event_name: "Mexico City Bachata Weekend",
    description: "A weekend of intensive Bachata workshops, social dancing, and performances from international artists.",
    location: "Hotel Reforma",
    address: "Paseo de la Reforma 135",
    city: "Mexico City",
    state: "CDMX",
    country: "Mexico",
    ticket_price: 95.00,
    currency: "MXN",
    event_type: "Workshop",
    event_category: "Bachata",
    image_url: "https://example.com/images/mexico-bachata.jpg",
    video_url: "https://example.com/videos/mexico-bachata.mp4",
    social_media: "https://instagram.com/mexicobachataweekend",
    website: "https://mexicobachataweekend.com",
    booking_url: "https://mexicobachataweekend.com/tickets",
    notes: "Partner recommended but not required."
  },
  {
    event_name: "Sydney West Coast Swing Open",
    description: "Australia's biggest West Coast Swing event with workshops, competitions, and social dancing every night.",
    location: "Sydney Convention Center",
    address: "14 Darling Drive",
    city: "Sydney",
    state: "New South Wales",
    country: "Australia",
    ticket_price: 200.00,
    currency: "AUD",
    event_type: "Competition",
    event_category: "West Coast Swing",
    image_url: "https://example.com/images/sydney-wcs.jpg",
    video_url: "https://example.com/videos/sydney-wcs.mp4",
    social_media: "https://instagram.com/sydneywcsopen",
    website: "https://sydneywcsopen.com",
    booking_url: "https://sydneywcsopen.com/register",
    notes: "All levels welcome, from newcomer to advanced."
  },
  {
    event_name: "Toronto Ballroom Gala",
    description: "An elegant evening of ballroom dancing with live orchestral music, professional showcases, and an open dance floor.",
    location: "Fairmont Royal York",
    address: "100 Front Street West",
    city: "Toronto",
    state: "Ontario",
    country: "Canada",
    ticket_price: 250.00,
    currency: "CAD",
    event_type: "Gala",
    event_category: "Ballroom",
    image_url: "https://example.com/images/toronto-ballroom.jpg",
    video_url: "https://example.com/videos/toronto-ballroom.mp4",
    social_media: "https://instagram.com/torontoballroomgala",
    website: "https://torontoballroomgala.com",
    booking_url: "https://torontoballroomgala.com/tickets",
    notes: "Formal attire required. Includes dinner and wine."
  },
  {
    event_name: "Havana Afro-Cuban Dance Festival",
    description: "Celebrate Afro-Cuban dance and music in the heart of Havana. Workshops, live music, and cultural experiences await.",
    location: "Havana Cultural Center",
    address: "Calle 23 y L",
    city: "Havana",
    state: "Havana",
    country: "Cuba",
    ticket_price: 60.00,
    currency: "CUP",
    event_type: "Festival",
    event_category: "Afro-Cuban",
    image_url: "https://example.com/images/havana-dance.jpg",
    video_url: "https://example.com/videos/havana-dance.mp4",
    social_media: "https://instagram.com/havanaafrocuban",
    website: "https://havanaafrocuban.com",
    booking_url: "https://havanaafrocuban.com/tickets",
    notes: "Workshops include Rumba, Orisha dance, and Son."
  },
  {
    event_name: "Rome Flamenco Fiesta",
    description: "An exhilarating showcase of Flamenco music and dance in the heart of Rome, featuring world-class performers and workshops.",
    location: "Teatro dell'Opera di Roma",
    address: "Piazza Beniamino Gigli 7",
    city: "Rome",
    state: "Lazio",
    country: "Italy",
    ticket_price: 85.00,
    currency: "EUR",
    event_type: "Concert",
    event_category: "Flamenco",
    image_url: "https://example.com/images/rome-flamenco.jpg",
    video_url: "https://example.com/videos/rome-flamenco.mp4",
    social_media: "https://instagram.com/romeflamenco",
    website: "https://romeflamenco.com",
    booking_url: "https://romeflamenco.com/tickets",
    notes: "Special guest performances by top Flamenco artists."
  },
  {
    event_name: "Berlin Breakdance Showdown",
    description: "An intense battle between the best breakdancers in Europe, featuring solo and crew battles, live DJs, and guest performances.",
    location: "Tempodrom",
    address: "Möckernstraße 10",
    city: "Berlin",
    state: "Berlin",
    country: "Germany",
    ticket_price: 50.00,
    currency: "EUR",
    event_type: "Battle",
    event_category: "Breakdance",
    image_url: "https://example.com/images/berlin-breakdance.jpg",
    video_url: "https://example.com/videos/berlin-breakdance.mp4",
    social_media: "https://instagram.com/berlinbreakshowdown",
    website: "https://berlinbreakshowdown.com",
    booking_url: "https://berlinbreakshowdown.com/tickets",
    notes: "Open cypher before the battles start. Cash prizes for winners."
  },
  {
    event_name: "San Diego Swing Dance Festival",
    description: "A three-day event celebrating Lindy Hop, Balboa, and Collegiate Shag with live bands, social dancing, and workshops.",
    location: "Balboa Park",
    address: "1549 El Prado",
    city: "San Diego",
    state: "California",
    country: "USA",
    ticket_price: 130.00,
    currency: "USD",
    event_type: "Festival",
    event_category: "Swing",
    image_url: "https://example.com/images/san-diego-swing.jpg",
    video_url: "https://example.com/videos/san-diego-swing.mp4",
    social_media: "https://instagram.com/sdswingfestival",
    website: "https://sdswingfestival.com",
    booking_url: "https://sdswingfestival.com/register",
    notes: "Beginner-friendly. No partner needed."
  },
  {
    event_name: "Lisbon Bachata Experience",
    description: "A weekend of Bachata workshops, rooftop parties, and live performances in the beautiful city of Lisbon.",
    location: "Lisbon Congress Center",
    address: "Praça das Indústrias",
    city: "Lisbon",
    state: "Lisbon",
    country: "Portugal",
    ticket_price: 100.00,
    currency: "EUR",
    event_type: "Workshop",
    event_category: "Bachata",
    image_url: "https://example.com/images/lisbon-bachata.jpg",
    video_url: "https://example.com/videos/lisbon-bachata.mp4",
    social_media: "https://instagram.com/lisbonbachata",
    website: "https://lisbonbachata.com",
    booking_url: "https://lisbonbachata.com/tickets",
    notes: "Discounted rates for group bookings."
  },
  {
    event_name: "Moscow Tango Festival",
    description: "A five-day celebration of Argentine Tango featuring world-class instructors, live orchestras, and milongas every night.",
    location: "Moscow House of Dance",
    address: "Tverskaya Street 25",
    city: "Moscow",
    state: "Moscow",
    country: "Russia",
    ticket_price: 90.00,
    currency: "RUB",
    event_type: "Festival",
    event_category: "Tango",
    image_url: "https://example.com/images/moscow-tango.jpg",
    video_url: "https://example.com/videos/moscow-tango.mp4",
    social_media: "https://instagram.com/moscowtangofestival",
    website: "https://moscowtangofestival.com",
    booking_url: "https://moscowtangofestival.com/tickets",
    notes: "Includes beginner-friendly classes and advanced workshops."
  },
  {
    event_name: "Shanghai Jazz & Dance Night",
    description: "A sophisticated evening of live jazz music and social dancing, featuring swing, blues, and fusion styles.",
    location: "The Pearl Shanghai",
    address: "471 Zhapu Road",
    city: "Shanghai",
    state: "Shanghai",
    country: "China",
    ticket_price: 55.00,
    currency: "CNY",
    event_type: "Party",
    event_category: "Jazz Dance",
    image_url: "https://example.com/images/shanghai-jazz.jpg",
    video_url: "https://example.com/videos/shanghai-jazz.mp4",
    social_media: "https://instagram.com/shanghaijazznight",
    website: "https://shanghaijazznight.com",
    booking_url: "https://shanghaijazznight.com/tickets",
    notes: "Includes a complimentary cocktail with entry."
  },
  {
    event_name: "Madrid Flamenco Festival",
    description: "Spain’s top flamenco festival, featuring workshops, live performances, and cultural events showcasing the essence of flamenco.",
    location: "Teatro Español",
    address: "Calle del Príncipe 25",
    city: "Madrid",
    state: "Madrid",
    country: "Spain",
    ticket_price: 75.00,
    currency: "EUR",
    event_type: "Festival",
    event_category: "Flamenco",
    image_url: "https://example.com/images/madrid-flamenco.jpg",
    video_url: "https://example.com/videos/madrid-flamenco.mp4",
    social_media: "https://instagram.com/madridflamenco",
    website: "https://madridflamenco.com",
    booking_url: "https://madridflamenco.com/tickets",
    notes: "Workshops available for all levels."
  },
  {
    event_name: "Rio Carnival Samba Parade",
    description: "Experience the world’s most famous carnival parade with stunning samba performances and breathtaking floats.",
    location: "Sambadrome Marquês de Sapucaí",
    address: "Av. Presidente Vargas",
    city: "Rio de Janeiro",
    state: "Rio de Janeiro",
    country: "Brazil",
    ticket_price: 200.00,
    currency: "BRL",
    event_type: "Parade",
    event_category: "Samba",
    image_url: "https://example.com/images/rio-carnival.jpg",
    video_url: "https://example.com/videos/rio-carnival.mp4",
    social_media: "https://instagram.com/riocarnival",
    website: "https://riocarnival.com",
    booking_url: "https://riocarnival.com/tickets",
    notes: "VIP seating available. Early booking recommended."
  },
  {
    event_name: "Chicago House Dance Conference",
    description: "A gathering of house dancers, DJs, and dance enthusiasts celebrating Chicago’s vibrant house dance scene.",
    location: "Navy Pier Ballroom",
    address: "600 E Grand Ave",
    city: "Chicago",
    state: "Illinois",
    country: "USA",
    ticket_price: 85.00,
    currency: "USD",
    event_type: "Conference",
    event_category: "House Dance",
    image_url: "https://example.com/images/chicago-house.jpg",
    video_url: "https://example.com/videos/chicago-house.mp4",
    social_media: "https://instagram.com/chicagohousedance",
    website: "https://chicagohousedance.com",
    booking_url: "https://chicagohousedance.com/tickets",
    notes: "Workshops and panel discussions included."
  },
  {
    event_name: "Cape Town Afro Dance Experience",
    description: "A fusion of traditional African dances with contemporary styles, featuring top instructors and vibrant dance parties.",
    location: "Cape Town International Convention Centre",
    address: "Convention Square",
    city: "Cape Town",
    state: "Western Cape",
    country: "South Africa",
    ticket_price: 70.00,
    currency: "ZAR",
    event_type: "Festival",
    event_category: "Afro Dance",
    image_url: "https://example.com/images/cape-town-afro.jpg",
    video_url: "https://example.com/videos/cape-town-afro.mp4",
    social_media: "https://instagram.com/capetownafrodance",
    website: "https://capetownafrodance.com",
    booking_url: "https://capetownafrodance.com/tickets",
    notes: "Special workshops on Afrobeat and Kizomba."
  },
  {
    event_name: "Athens Latin Nights",
    description: "An exclusive Latin dance party in Athens featuring top DJs, guest performances, and an open dance floor all night long.",
    location: "Gazarte Club",
    address: "Voutadon 32",
    city: "Athens",
    state: "Attica",
    country: "Greece",
    ticket_price: 30.00,
    currency: "EUR",
    event_type: "Party",
    event_category: "Latin Dance",
    image_url: "https://example.com/images/athens-latin.jpg",
    video_url: "https://example.com/videos/athens-latin.mp4",
    social_media: "https://instagram.com/athenslatinnights",
    website: "https://athenslatinnights.com",
    booking_url: "https://athenslatinnights.com/tickets",
    notes: "Free salsa class before the party starts."
  },
  {
    event_name: "Amsterdam Latin Festival",
    description: "A weekend filled with Salsa, Bachata, and Kizomba workshops, social parties, and live performances by top Latin artists.",
    location: "RAI Amsterdam",
    address: "Europaplein 24",
    city: "Amsterdam",
    state: "North Holland",
    country: "Netherlands",
    ticket_price: 110.00,
    currency: "EUR",
    event_type: "Festival",
    event_category: "Latin Dance",
    image_url: "https://example.com/images/amsterdam-latin.jpg",
    video_url: "https://example.com/videos/amsterdam-latin.mp4",
    social_media: "https://instagram.com/amsterdamlatinfestival",
    website: "https://amsterdamlatinfestival.com",
    booking_url: "https://amsterdamlatinfestival.com/tickets",
    notes: "Early bird tickets available until February 15th."
  },
  {
    event_name: "Prague Tango Weekend",
    description: "A romantic weekend of Tango workshops, milongas, and live performances in the historic city of Prague.",
    location: "Prague Congress Center",
    address: "5. května 65",
    city: "Prague",
    state: "Prague",
    country: "Czech Republic",
    ticket_price: 80.00,
    currency: "CZK",
    event_type: "Weekend",
    event_category: "Tango",
    image_url: "https://example.com/images/prague-tango.jpg",
    video_url: "https://example.com/videos/prague-tango.mp4",
    social_media: "https://instagram.com/praguetangoweekend",
    website: "https://praguetangoweekend.com",
    booking_url: "https://praguetangoweekend.com/register",
    notes: "Milonga pass included in full weekend package."
  },
  {
    event_name: "Los Angeles Dance Fusion",
    description: "A unique blend of Urban, Latin, and Afro dance styles featuring top choreographers and a spectacular closing showcase.",
    location: "Hollywood Dance Center",
    address: "6725 Sunset Blvd",
    city: "Los Angeles",
    state: "California",
    country: "USA",
    ticket_price: 140.00,
    currency: "USD",
    event_type: "Festival",
    event_category: "Fusion",
    image_url: "https://example.com/images/la-dance-fusion.jpg",
    video_url: "https://example.com/videos/la-dance-fusion.mp4",
    social_media: "https://instagram.com/lafusiondance",
    website: "https://lafusiondance.com",
    booking_url: "https://lafusiondance.com/tickets",
    notes: "Workshops available for all levels."
  },
  {
    event_name: "Beijing Ballroom Championship",
    description: "A prestigious ballroom dance competition featuring Waltz, Foxtrot, Quickstep, and Latin categories.",
    location: "Beijing National Convention Center",
    address: "7 Tianchen East Road",
    city: "Beijing",
    state: "Beijing",
    country: "China",
    ticket_price: 200.00,
    currency: "CNY",
    event_type: "Competition",
    event_category: "Ballroom",
    image_url: "https://example.com/images/beijing-ballroom.jpg",
    video_url: "https://example.com/videos/beijing-ballroom.mp4",
    social_media: "https://instagram.com/beijingballroom",
    website: "https://beijingballroom.com",
    booking_url: "https://beijingballroom.com/register",
    notes: "Judges from the World Dance Federation."
  },
  {
    event_name: "Hong Kong Kizomba Nights",
    description: "A monthly Kizomba party with live DJs, guest instructors, and a beautiful waterfront venue.",
    location: "Sky Lounge HK",
    address: "88 Queensway",
    city: "Hong Kong",
    state: "Hong Kong",
    country: "China",
    ticket_price: 40.00,
    currency: "HKD",
    event_type: "Party",
    event_category: "Kizomba",
    image_url: "https://example.com/images/hk-kizomba.jpg",
    video_url: "https://example.com/videos/hk-kizomba.mp4",
    social_media: "https://instagram.com/hkkizombanights",
    website: "https://hkkizombanights.com",
    booking_url: "https://hkkizombanights.com/tickets",
    notes: "Free beginner class before the party starts."
  },
  {
    event_name: "Helsinki Urban Dance Festival",
    description: "A weekend packed with hip hop, house, and street dance battles, performances, and masterclasses.",
    location: "Helsinki Ice Hall",
    address: "Nordenskiöldinkatu 11-13",
    city: "Helsinki",
    state: "Uusimaa",
    country: "Finland",
    ticket_price: 90.00,
    currency: "EUR",
    event_type: "Festival",
    event_category: "Hip Hop",
    image_url: "https://example.com/images/helsinki-urban.jpg",
    video_url: "https://example.com/videos/helsinki-urban.mp4",
    social_media: "https://instagram.com/helsinkiurbanfestival",
    website: "https://helsinkiurbanfestival.com",
    booking_url: "https://helsinkiurbanfestival.com/tickets",
    notes: "All ages and levels welcome."
  },
  {
    event_name: "Melbourne Zouk Weekender",
    description: "An immersive Zouk experience with top instructors, beach parties, and social dancing every night.",
    location: "Melbourne Town Hall",
    address: "90-130 Swanston St",
    city: "Melbourne",
    state: "Victoria",
    country: "Australia",
    ticket_price: 120.00,
    currency: "AUD",
    event_type: "Weekend",
    event_category: "Zouk",
    image_url: "https://example.com/images/melbourne-zouk.jpg",
    video_url: "https://example.com/videos/melbourne-zouk.mp4",
    social_media: "https://instagram.com/melbournezoukweekender",
    website: "https://melbournezoukweekender.com",
    booking_url: "https://melbournezoukweekender.com/tickets",
    notes: "Workshops for all levels, no partner required."
  },
  {
    event_name: "Dubai Belly Dance Gala",
    description: "A dazzling showcase of belly dance performances, featuring world-class dancers and live musicians.",
    location: "Dubai Opera",
    address: "Sheikh Mohammed bin Rashid Blvd",
    city: "Dubai",
    state: "Dubai",
    country: "UAE",
    ticket_price: 150.00,
    currency: "AED",
    event_type: "Gala",
    event_category: "Belly Dance",
    image_url: "https://example.com/images/dubai-bellydance.jpg",
    video_url: "https://example.com/videos/dubai-bellydance.mp4",
    social_media: "https://instagram.com/dubaibellydancegala",
    website: "https://dubaibellydancegala.com",
    booking_url: "https://dubaibellydancegala.com/tickets",
    notes: "Dress code: Elegant. VIP seating available."
  },
  {
    event_name: "Buenos Aires Folklore Festival",
    description: "A vibrant celebration of traditional Argentine folklore music and dance, featuring live bands and dance competitions.",
    location: "Luna Park Stadium",
    address: "Av. Madero 420",
    city: "Buenos Aires",
    state: "Buenos Aires",
    country: "Argentina",
    ticket_price: 80.00,
    currency: "ARS",
    event_type: "Festival",
    event_category: "Folklore",
    image_url: "https://example.com/images/buenos-aires-folklore.jpg",
    video_url: "https://example.com/videos/buenos-aires-folklore.mp4",
    social_media: "https://instagram.com/bafolklore",
    website: "https://bafolklore.com",
    booking_url: "https://bafolklore.com/tickets",
    notes: "Traditional dance workshops included."
  },
  {
    event_name: "Mexico City Salsa Championship",
    description: "The ultimate Salsa competition in Mexico, featuring the best dancers from across the country and international guests.",
    location: "Pepsi Center WTC",
    address: "Dakota 95",
    city: "Mexico City",
    state: "CDMX",
    country: "Mexico",
    ticket_price: 95.00,
    currency: "MXN",
    event_type: "Competition",
    event_category: "Salsa",
    image_url: "https://example.com/images/mexico-salsa.jpg",
    video_url: "https://example.com/videos/mexico-salsa.mp4",
    social_media: "https://instagram.com/mexicosalsachampionship",
    website: "https://mexicosalsachampionship.com",
    booking_url: "https://mexicosalsachampionship.com/register",
    notes: "Winners qualify for the World Salsa Championship."
  },
  {
    event_name: "Tokyo Bachata Festival",
    description: "A weekend of Bachata passion with international artists, workshops, and breathtaking performances in the heart of Tokyo.",
    location: "Shinjuku Cultural Center",
    address: "5-3-1 Shinjuku",
    city: "Tokyo",
    state: "Tokyo",
    country: "Japan",
    ticket_price: 140.00,
    currency: "JPY",
    event_type: "Festival",
    event_category: "Bachata",
    image_url: "https://example.com/images/tokyo-bachata.jpg",
    video_url: "https://example.com/videos/tokyo-bachata.mp4",
    social_media: "https://instagram.com/tokyobachatafestival",
    website: "https://tokyobachatafestival.com",
    booking_url: "https://tokyobachatafestival.com/tickets",
    notes: "Workshops for all levels, no partner required."
  },
  {
    event_name: "Paris Kizomba Connection",
    description: "The ultimate Kizomba experience in the romantic city of Paris, featuring top instructors, dance parties, and live music.",
    location: "La Bellevilloise",
    address: "19-21 Rue Boyer",
    city: "Paris",
    state: "Île-de-France",
    country: "France",
    ticket_price: 85.00,
    currency: "EUR",
    event_type: "Weekend",
    event_category: "Kizomba",
    image_url: "https://example.com/images/paris-kizomba.jpg",
    video_url: "https://example.com/videos/paris-kizomba.mp4",
    social_media: "https://instagram.com/pariskizombaconnection",
    website: "https://pariskizombaconnection.com",
    booking_url: "https://pariskizombaconnection.com/tickets",
    notes: "Dance socials every night of the event."
  },
  {
    event_name: "Barcelona Flamenco Nights",
    description: "An intimate flamenco experience with passionate live performances and authentic Spanish cuisine in the heart of Barcelona.",
    location: "El Tablao de Carmen",
    address: "Avenida de Francesc Ferrer i Guàrdia",
    city: "Barcelona",
    state: "Catalonia",
    country: "Spain",
    ticket_price: 75.00,
    currency: "EUR",
    event_type: "Show",
    event_category: "Flamenco",
    image_url: "https://example.com/images/barcelona-flamenco.jpg",
    video_url: "https://example.com/videos/barcelona-flamenco.mp4",
    social_media: "https://instagram.com/barcelonaflamenconights",
    website: "https://barcelonaflamenconights.com",
    booking_url: "https://barcelonaflamenconights.com/tickets",
    notes: "Dinner and drinks package available."
  },
  {
    event_name: "New Orleans Jazz & Swing Festival",
    description: "Swing your way through a weekend of live jazz bands, dance competitions, and social dancing in the heart of New Orleans.",
    location: "Preservation Hall",
    address: "726 St Peter",
    city: "New Orleans",
    state: "Louisiana",
    country: "USA",
    ticket_price: 95.00,
    currency: "USD",
    event_type: "Festival",
    event_category: "Swing",
    image_url: "https://example.com/images/new-orleans-jazz.jpg",
    video_url: "https://example.com/videos/new-orleans-jazz.mp4",
    social_media: "https://instagram.com/nolajazzswing",
    website: "https://nolajazzswing.com",
    booking_url: "https://nolajazzswing.com/tickets",
    notes: "Live swing bands playing all weekend."
  },
  {
    event_name: "Toronto Afro-Latin Dance Congress",
    description: "An explosive celebration of Afro-Latin dance styles with world-renowned instructors, parties, and shows.",
    location: "Metro Toronto Convention Centre",
    address: "255 Front St W",
    city: "Toronto",
    state: "Ontario",
    country: "Canada",
    ticket_price: 150.00,
    currency: "CAD",
    event_type: "Congress",
    event_category: "Afro-Latin",
    image_url: "https://example.com/images/toronto-afro-latin.jpg",
    video_url: "https://example.com/videos/toronto-afro-latin.mp4",
    social_media: "https://instagram.com/torontoafrolatin",
    website: "https://torontoafrolatincongress.com",
    booking_url: "https://torontoafrolatincongress.com/tickets",
    notes: "Discounted rates for group passes."
  },
  {
    event_name: "Sydney Tango Extravaganza",
    description: "A mesmerizing weekend of tango with international maestros, stunning performances, and elegant milongas in Sydney.",
    location: "Sydney Opera House",
    address: "Bennelong Point",
    city: "Sydney",
    state: "New South Wales",
    country: "Australia",
    ticket_price: 120.00,
    currency: "AUD",
    event_type: "Festival",
    event_category: "Tango",
    image_url: "https://example.com/images/sydney-tango.jpg",
    video_url: "https://example.com/videos/sydney-tango.mp4",
    social_media: "https://instagram.com/sydneytangoextravaganza",
    website: "https://sydneytangoextravaganza.com",
    booking_url: "https://sydneytangoextravaganza.com/tickets",
    notes: "VIP seating available."
  },
  {
    event_name: "Rio de Janeiro Samba Bootcamp",
    description: "Learn the art of Samba with the best Brazilian instructors, leading up to a live performance at a street parade.",
    location: "Centro Cultural Banco do Brasil",
    address: "Rua Primeiro de Março 66",
    city: "Rio de Janeiro",
    state: "Rio de Janeiro",
    country: "Brazil",
    ticket_price: 80.00,
    currency: "BRL",
    event_type: "Workshop",
    event_category: "Samba",
    image_url: "https://example.com/images/rio-samba.jpg",
    video_url: "https://example.com/videos/rio-samba.mp4",
    social_media: "https://instagram.com/riosambabootcamp",
    website: "https://riosambabootcamp.com",
    booking_url: "https://riosambabootcamp.com/register",
    notes: "Includes a costume for the final parade."
  },
  {
    event_name: "Cape Town Salsa Social",
    description: "A vibrant social dancing event with guest DJs, salsa workshops, and breathtaking views of Cape Town’s skyline.",
    location: "The Grand Café & Beach",
    address: "Haul Road, Granger Bay",
    city: "Cape Town",
    state: "Western Cape",
    country: "South Africa",
    ticket_price: 40.00,
    currency: "ZAR",
    event_type: "Party",
    event_category: "Salsa",
    image_url: "https://example.com/images/cape-town-salsa.jpg",
    video_url: "https://example.com/videos/cape-town-salsa.mp4",
    social_media: "https://instagram.com/capetownsalsasocial",
    website: "https://capetownsalsasocial.com",
    booking_url: "https://capetownsalsasocial.com/tickets",
    notes: "Free beginner class before the party."
  },
  {
    event_name: "Vienna Waltz Night",
    description: "Step back in time and experience a magical evening of Viennese Waltz in an opulent ballroom setting.",
    location: "Hofburg Palace",
    address: "Michaelerkuppel",
    city: "Vienna",
    state: "Vienna",
    country: "Austria",
    ticket_price: 250.00,
    currency: "EUR",
    event_type: "Gala",
    event_category: "Ballroom",
    image_url: "https://example.com/images/vienna-waltz.jpg",
    video_url: "https://example.com/videos/vienna-waltz.mp4",
    social_media: "https://instagram.com/viennawaltznight",
    website: "https://viennawaltznight.com",
    booking_url: "https://viennawaltznight.com/tickets",
    notes: "Formal dress code required."
  }
]

events_data.each do |event_data|
  Event.create!(event_data)
end
